echo "************************************************"
echo "*                                              *"
echo "* Run these statements from the command line   *"
echo "*                                              *"
echo "************************************************"
echo "conda create --name=pyFileUnpacker python=3.7 -y"
echo "conda activate pyFileUnpacker"
echo "pip install --upgrade pip"
echo "pip install -r requirements.txt"
